<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ModelsBorrowHistoryHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data)
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = (string) $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['user'])) {
            $reference = $data['user'];
            $className = $this->dm->getClassNameFromDiscriminatorValue($this->class->fieldMappings['user'], $reference);
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($reference['$id']);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['user']->setValue($document, $return);
            $hydratedData['user'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['book'])) {
            $reference = $data['book'];
            $className = $this->dm->getClassNameFromDiscriminatorValue($this->class->fieldMappings['book'], $reference);
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($reference['$id']);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['book']->setValue($document, $return);
            $hydratedData['book'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['startBorrowDate'])) {
            $value = $data['startBorrowDate'];
            $return = (string) $value;
            $this->class->reflFields['startBorrowDate']->setValue($document, $return);
            $hydratedData['startBorrowDate'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['planReturnDate'])) {
            $value = $data['planReturnDate'];
            $return = (string) $value;
            $this->class->reflFields['planReturnDate']->setValue($document, $return);
            $hydratedData['planReturnDate'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['realReturnDate'])) {
            $value = $data['realReturnDate'];
            $return = (string) $value;
            $this->class->reflFields['realReturnDate']->setValue($document, $return);
            $hydratedData['realReturnDate'] = $return;
        }
        return $hydratedData;
    }
}