<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ModelsBookHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data)
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = (string) $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['BianHao'])) {
            $value = $data['BianHao'];
            $return = (string) $value;
            $this->class->reflFields['BianHao']->setValue($document, $return);
            $hydratedData['BianHao'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['title'])) {
            $value = $data['title'];
            $return = (string) $value;
            $this->class->reflFields['title']->setValue($document, $return);
            $hydratedData['title'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['description'])) {
            $value = $data['description'];
            $return = (string) $value;
            $this->class->reflFields['description']->setValue($document, $return);
            $hydratedData['description'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['author'])) {
            $value = $data['author'];
            $return = (string) $value;
            $this->class->reflFields['author']->setValue($document, $return);
            $hydratedData['author'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['publishedDate'])) {
            $value = $data['publishedDate'];
            $return = (string) $value;
            $this->class->reflFields['publishedDate']->setValue($document, $return);
            $hydratedData['publishedDate'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['publisher'])) {
            $value = $data['publisher'];
            $return = (string) $value;
            $this->class->reflFields['publisher']->setValue($document, $return);
            $hydratedData['publisher'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['language'])) {
            $value = $data['language'];
            $return = (string) $value;
            $this->class->reflFields['language']->setValue($document, $return);
            $hydratedData['language'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['printLength'])) {
            $value = $data['printLength'];
            $return = (int) $value;
            $this->class->reflFields['printLength']->setValue($document, $return);
            $hydratedData['printLength'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['ISBN'])) {
            $value = $data['ISBN'];
            $return = (string) $value;
            $this->class->reflFields['ISBN']->setValue($document, $return);
            $hydratedData['ISBN'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['image'])) {
            $value = $data['image'];
            $return = (string) $value;
            $this->class->reflFields['image']->setValue($document, $return);
            $hydratedData['image'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['price'])) {
            $value = $data['price'];
            $return = (string) $value;
            $this->class->reflFields['price']->setValue($document, $return);
            $hydratedData['price'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['EnterLibraryTime'])) {
            $value = $data['EnterLibraryTime'];
            $return = (int) $value;
            $this->class->reflFields['EnterLibraryTime']->setValue($document, $return);
            $hydratedData['EnterLibraryTime'] = $return;
        }
        return $hydratedData;
    }
}