<?php

namespace Proxies;

use Doctrine\ODM\MongoDB\Persisters\DocumentPersister;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ModelsBookProxy extends \Models\Book implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    private $__documentPersister__;
    private $__identifier__;
    public $__isInitialized__ = false;
    public function __construct(DocumentPersister $documentPersister, $identifier)
    {
        $this->__documentPersister__ = $documentPersister;
        $this->__identifier__ = $identifier;
    }
    private function __load()
    {
        if (!$this->__isInitialized__ && $this->__documentPersister__) {
            $this->__isInitialized__ = true;
            if ($this->__documentPersister__->load($this->__identifier__, $this) === null) {
                throw \Doctrine\ODM\MongoDB\MongoDBException::documentNotFound(get_class($this), $this->__identifier__);
            }
            unset($this->__documentPersister__, $this->__identifier__);
        }
    }

    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function GetTitle()
    {
        $this->__load();
        return parent::GetTitle();
    }

    public function GetBianHao()
    {
        $this->__load();
        return parent::GetBianHao();
    }

    public function GetAuthor()
    {
        $this->__load();
        return parent::GetAuthor();
    }

    public function setAuthor($author)
    {
        $this->__load();
        return parent::setAuthor($author);
    }

    public function GetDescription()
    {
        $this->__load();
        return parent::GetDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getPrintLength()
    {
        $this->__load();
        return parent::getPrintLength();
    }

    public function setPrintLength($printLength)
    {
        $this->__load();
        return parent::setPrintLength($printLength);
    }

    public function getPublishedDate()
    {
        $this->__load();
        return parent::getPublishedDate();
    }

    public function setPublishedDate($publishedDate)
    {
        $this->__load();
        return parent::setPublishedDate($publishedDate);
    }

    public function getPublisher()
    {
        $this->__load();
        return parent::getPublisher();
    }

    public function setPublisher($publisher)
    {
        $this->__load();
        return parent::setPublisher($publisher);
    }

    public function getLanguage()
    {
        $this->__load();
        return parent::getLanguage();
    }

    public function setLanguage($language)
    {
        $this->__load();
        return parent::setLanguage($language);
    }

    public function getISBN()
    {
        $this->__load();
        return parent::getISBN();
    }

    public function setISBN($isbn)
    {
        $this->__load();
        return parent::setISBN($isbn);
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function setPrice($price)
    {
        $this->__load();
        return parent::setPrice($price);
    }


    public function __sleep()
    {
        return array('id', 'BianHao', 'title', 'description', 'author', 'publishedDate', 'publisher', 'language', 'printLength', 'ISBN', 'image', 'price', 'EnterLibraryTime');
    }
}